version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: zenconnect-postgres
    environment:
      POSTGRES_DB: zenconnect
      POSTGRES_USER: zenconnect
      POSTGRES_PASSWORD: zenconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenconnect"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: